// src/app/page.tsx
import db from '@/../db.json'
import Image from 'next/image'

import { AspectRatio } from "@/components/ui/aspect-ratio"

export default function Home() {
  return (
    <main>
      {/* <section className="flex min-h-screen bg-red-100 w-full">
        Main
      </section>

      <section className="w-full bg-yellow-100">
        {db.cities.length}
      </section> */}

      <section className="flex flex-wrap gap-4 bg-green-100 justify-center p-4">
        {db.cities.map(city => {
          return (
            <div key={city.slug} className="flex w-full sm:w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/5 bg-red-100 relative">
              <AspectRatio ratio={16 / 9} className="bg-muted">
                <Image
                  fill
                  alt={city.name}
                  src={city.image}
                  className="rounded-md object-cover"
                />
                <div className="absolute inset-0 bg-black bg-opacity-15 rounded-md" />
                <div className="text-white absolute inset-0 flex flex-col items-center justify-center bg-opacity-50">
                  <h2 className="text-2xl font-bold">{city.name}</h2>
                  <p className="text-lg">{city.country}</p>
                </div>
              </AspectRatio>
            </div>
          )
        })}
      </section>
    </main>
  );
}

// src/app.vue
<template>
  <div class="min-h-screen bg-gray-100 text-gray-900">
    <section class="bg-blue-600 text-white py-20 text-center">
      <h1 class="text-5xl font-bold">Explore. Work. Live.</h1>
      <p class="mt-4 text-lg">Find the perfect city for your digital nomad lifestyle.</p>
      <div class="mt-6">
        <input 
          type="text" 
          placeholder="Search for a city..." 
          class="w-3/4 p-3 rounded-lg text-gray-900 focus:outline-none"
        />
      </div>
    </section>

    <section class="py-12 px-6 grid grid-cols-1 lg:grid-cols-6 gap-6">
      <aside class="lg:col-span-1 rounded-2xl p-6">
        <h3 class="text-xl font-bold">Filters</h3>
        <template v-if="data">
          <div v-for="filterKey of Object.keys(data.filters ?? {})" :key="filterKey" class="mb-4">
            <label :for="filterKey" class="block text-sm font-medium text-gray-700">{{ upperFirst(filterKey) }}</label>
            <select :id="filterKey" class="w-full p-3 mt-2 border rounded-lg">
              <option value="">All {{ filterKey }}</option>
              <option v-for="option of data.filters[filterKey as keyof typeof data['filters']].options" :value="option">{{ option }}</option>
            </select>
          </div>
        </template>
      </aside>

      <div class="lg:col-span-5 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        <div v-for="city in data?.cities" :key="city.slug" class="bg-white shadow-xl rounded-xl transition-all transform hover:scale-105 hover:shadow-2xl">
          <img :src="city.image" :alt="city.name" class="rounded-lg w-full object-cover">
          <div class="p-3 flex flex-col gap-3">
            <h3 class="text-xl font-semibold text-gray-900">{{ city.name }}, {{ city.country }}</h3>
            <p class="text-sm text-gray-600">Population: {{ city.population }}</p>
            <div class="flex justify-between text-sm">
              <span class="text-blue-500">☀️ {{ city.temperatureC }}°C</span>
              <span class="text-green-500">💰 ${{ city.costForNomadInUsd }}/mo</span>
              <span class="text-yellow-500">🌐 {{ city.internetSpeed }} Mbps</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import upperFirst from 'lodash/upperFirst';

const { data } = await useFetch('/api/cities')
</script>
